server:
  port: 8080
spring:
  datasource:
    username: avnadmin
    password: AVNS_EDlZev1SK0umpFPSWyE
    url: jdbc:postgresql://gym-fitness-app-gym-fitness-app.a.aivencloud.com:13351/gym_fitness_app?ssl=require&user=avnadmin&password=AVNS_EDlZev1SK0umpFPSWyE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ikromova702@gmail.com
    password: sjuh ojto kntm epcr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  security:
    jwt:
      token:
        expiration: 864000
        secret: WC+qbHYl2B0o02421L+2UayDp2LtczY/3cSkAyErfTjmcEOXNtyjXq0un/SdY4cw
gsc:
  serviceAccountKeyPath: ${GOOGLE_CLOUD_CREDENTIALS}