server:
  port: 8080
spring:
  datasource:
    username: postgres
    password: 5825
    url: jdbc:postgresql://localhost:5432/gym_fitness_app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ikromova702@gmail.com
    password: sjuh ojto kntm epcr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  security:
    jwt:
      token:
        expiration: 864000
        secret: WC+qbHYl2B0o02421L+2UayDp2LtczY/3cSkAyErfTjmcEOXNtyjXq0un/SdY4cw
gsc:
  serviceAccountKeyPath: src/main/resources/my-project-411810-2d2eae1caef7.json