server:
  port: 8080
spring:
  datasource:
   username: postgres
   password: rut123
   password: 5825
   url: jdbc:postgresql://localhost:5432/gym_fitness_app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true