server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true